version: '2.1'
services:
    db:
        build: mysql/.
        image: 'sql'
        container_name: db
        ports:
            - "32000:3306"
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: users
            MYSQL_USER: root
            MYSQL_PASSWORD: root
        healthcheck:
            test: "exit 0"
        volumes:
            - ./db:/docker-entrypoint-initdb.d/:ro
        restart: unless-stopped
    flask:
        build: .
        image: python:2.7
        container_name: flask_app
        stdin_open: true
        tty: true
        working_dir: /app
        links:
            - db:db
        ports:
            - "5000:5000"
        environment:
            - DATABASE_HOST=db
        volumes:
            - .:/app
        depends_on:
            db: 
                condition: service_healthy
        restart: unless-stopped 

       
       
       
        

